[tool.poetry]
name = "kozmoai-nasdaq"
version = "1.4.0"
description = "Nasdaq extension for KozmoAI"
authors = ["KozmoAI Team <hello@kozmoai.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "kozmoai_nasdaq" }]

[tool.poetry.dependencies]
python = "^3.9"
kozmoai-core = "^1.4.2"
random-user-agent = "^1.0.1"
nasdaq-data-link = "^1.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."kozmoai_provider_extension"]
nasdaq = "kozmoai_nasdaq:nasdaq_provider"
