[tool.poetry]
name = "kozmoai-intrinio"
version = "1.4.0"
description = "Intrinio extension for KozmoAI"
authors = ["KozmoAI Team <hello@kozmoai.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "kozmoai_intrinio" }]

[tool.poetry.dependencies]
python = "^3.9"
requests-cache = "^1.1.0"
kozmoai-core = "^1.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."kozmoai_provider_extension"]
intrinio = "kozmoai_intrinio:intrinio_provider"
