[tool.poetry]
name = "kozmoai-tmx"
version = "1.3.0"
description = "Unofficial TMX data provider extension for the KozmoAI Platform - Public Canadian markets data for Python and Fast API."
authors = ["KozmoAI <hello@kozmoai.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "kozmoai_tmx" }]

[tool.poetry.dependencies]
python = "^3.9"
aiohttp-client-cache = "^0.11.0"
aiosqlite = "^0.20.0"
random-user-agent = "^1.0.1"
exchange-calendars = "^4.5.4"
kozmoai-core = "^1.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."kozmoai_provider_extension"]
tmx = "kozmoai_tmx:tmx_provider"
