[tool.poetry]
name = "kozmoai-multpl"
version = "1.1.0"
description = "Public data on historical S&P Multiples."
authors = ["KozmoAI Team <hello@kozmoai.co>"]
readme = "README.md"
packages = [{ include = "kozmoai_multpl" }]

[tool.poetry.dependencies]
python = "^3.9,<3.13"
kozmoai-core = "^1.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."kozmoai_provider_extension"]
multpl = "kozmoai_multpl:multpl_provider"
