[tool.poetry]
name = "kozmoai-yfinance"
version = "1.4.1"
description = "yfinance extension for KozmoAI"
authors = ["KozmoAI Team <hello@kozmoai.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "kozmoai_yfinance" }]

[tool.poetry.dependencies]
python = "^3.9"
yfinance = "^0.2.54"
kozmoai-core = "^1.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."kozmoai_provider_extension"]
yfinance = "kozmoai_yfinance:yfinance_provider"
