[tool.poetry]
name = "kozmoai-tradier"
version = "1.3.0"
description = "Tradier Provider Extension for the KozmoAI Platform"
authors = ["KozmoAI <hello@kozmoai.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "kozmoai_tradier" }]

[tool.poetry.dependencies]
python = "^3.9"
kozmoai-core = "^1.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."kozmoai_provider_extension"]
tradier = "kozmoai_tradier:tradier_provider"
