[tool.poetry]
name = "kozmoai-oecd"
version = "1.4.0"
description = "OECD extension for KozmoAI"
authors = ["KozmoAI Team <hello@kozmoai.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "kozmoai_oecd" }]

[tool.poetry.dependencies]
python = "^3.9"
kozmoai-core = "^1.4.2"
urllib3 = ">1.26.16"
defusedxml = "^0.8.0rc2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."kozmoai_provider_extension"]
oecd = "kozmoai_oecd:oecd_provider"
