name: Deploy to PyPI - Nightly

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-nightly-pypi:
    name: Build and publish nightly distributions 📦 to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: >-
          python -m
          pip install
          build
          poetry
          toml

      - name: KozmoAI Platform - Update version in pyproject.toml
        working-directory: marketplace/quant/kozmoai_platform
        run: |
          sed -i 's/name = ".*"/name = "kozmoai-nightly"/' pyproject.toml
          sed -i "3s/version = \"\(.*\)\"/version = \"\1.dev$(date +%Y%m%d%H%M)\"/" pyproject.toml
          echo "Updated version in pyproject.toml"

      - name: KozmoAI Platform - Create the dynamically generated wheel
        working-directory: marketplace/quant
        run: |
          if [ -f "build/pypi/kozmoai_platform/nightly.py" ]; then
            python build/pypi/kozmoai_platform/nightly.py
          else
            cd kozmoai_platform
            python -m build
            echo "Built package using standard build process"
          fi

      - name: KozmoAI Platform - Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: marketplace/quant/kozmoai_platform/dist/
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true

  deploy-pandas-ta-kozmoai:
    name: Build and publish pandas-ta-kozmoai 📦 to PyPI
    runs-on: ubuntu-latest
    outputs:
      PANDAS_TA_VERSION: ${{ steps.set_version.outputs.PANDAS_TA_VERSION }}
      PANDAS_TA_REPOSITORY: ${{ steps.publish.outputs.REPOSITORY }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: >-
          python -m
          pip install
          build
          poetry

      - name: Update pandas-ta-kozmoai version
        id: set_version
        working-directory: marketplace/quant/pandas_ta_kozmoai
        run: |
          # Add dev suffix with timestamp to version
          TIMESTAMP=$(date +%Y%m%d%H%M)
          sed -i "3s/version = \"\(.*\)\"/version = \"\1.dev$TIMESTAMP\"/" pyproject.toml
          echo "Updated pandas-ta-kozmoai version to include timestamp: $TIMESTAMP"
          # Store the version for later use
          VERSION=$(grep -oP 'version = "\K[^"]+' pyproject.toml)
          echo "PANDAS_TA_VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "PANDAS_TA_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build pandas-ta-kozmoai package
        working-directory: marketplace/quant/pandas_ta_kozmoai
        run: |
          # Build the package
          python -m build
          echo "Built pandas-ta-kozmoai package version ${{ env.PANDAS_TA_VERSION }}"

      - name: Publish pandas-ta-kozmoai to PyPI
        id: publish
        continue-on-error: true
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: marketplace/quant/pandas_ta_kozmoai/dist/
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true

      - name: Check if PyPI upload failed due to rate limits
        if: steps.publish.outcome == 'failure'
        run: |
          echo "PyPI upload failed. Falling back to TestPyPI."
          echo "REPOSITORY=testpypi" >> $GITHUB_OUTPUT
        id: check_failure

      - name: Publish pandas-ta-kozmoai to TestPyPI if PyPI failed
        if: steps.check_failure.outcome == 'success'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: marketplace/quant/pandas_ta_kozmoai/dist/
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
        
      - name: Set repository output
        id: repository
        if: steps.check_failure.outcome != 'success'
        run: |
          echo "REPOSITORY=pypi" >> $GITHUB_OUTPUT

  deploy-extensions:
    name: Build and publish ${{ matrix.extension }} extension 📦 to PyPI
    runs-on: ubuntu-latest
    needs: deploy-pandas-ta-kozmoai
    strategy:
      fail-fast: false
      matrix:
        extension:
          - technical
          - quantitative
          - platform_api
          - econometrics
          - fixedincome
          - derivatives
          - regulators
          - commodity
          - devtools
          - currency
          - economy
          - equity
          - crypto
          - index
          - news
          - etf
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: >-
          python -m
          pip install
          build
          poetry
          toml
          yq

      - name: Verify extension directory exists
        id: check_extension
        run: |
          if [ -d "marketplace/quant/kozmoai_platform/extensions/${{ matrix.extension }}" ]; then
            echo "extension_exists=true" >> $GITHUB_OUTPUT
          else
            echo "extension_exists=false" >> $GITHUB_OUTPUT
            echo "Extension ${{ matrix.extension }} directory not found, skipping."
          fi

      - name: Replace file-based dependencies with version constraints
        if: steps.check_extension.outputs.extension_exists == 'true'
        working-directory: marketplace/quant/kozmoai_platform/extensions/${{ matrix.extension }}
        run: |
          if [ -f "pyproject.toml" ]; then
            # Create a backup of the original pyproject.toml
            cp pyproject.toml pyproject.toml.backup
            
            # Check if file contains pandas-ta-kozmoai as a file reference
            if grep -q "pandas-ta-kozmoai.*path" pyproject.toml; then
              echo "Found file-based pandas-ta-kozmoai dependency, replacing with version reference"
              # Replace the file-based dependency with the version from previous job
              PANDAS_TA_VERSION="${{ needs.deploy-pandas-ta-kozmoai.outputs.PANDAS_TA_VERSION || '0.4.21' }}"
              
              # Use sed to replace the path-based dependency with a version constraint
              sed -i 's|pandas-ta-kozmoai = { path = "[^"]*", develop = true }|pandas-ta-kozmoai = "'"$PANDAS_TA_VERSION"'"|g' pyproject.toml
              echo "Replaced pandas-ta-kozmoai path dependency with version: $PANDAS_TA_VERSION"
              
              # Add the appropriate index-url if using TestPyPI
              if [ "${{ needs.deploy-pandas-ta-kozmoai.outputs.REPOSITORY }}" = "testpypi" ]; then
                # Add a pyproject.toml section for the test.pypi.org index
                awk 'BEGIN{p=1}/\[build-system\]/{print "[tool.poetry.source.testpypi]\nname = \"testpypi\"\nurl = \"https://test.pypi.org/simple/\"\npriority = \"supplemental\"\n"}p' pyproject.toml > pyproject.toml.tmp
                mv pyproject.toml.tmp pyproject.toml
                echo "Added TestPyPI source to pyproject.toml"
              fi
            fi
            
            # Handle any other file-based dependencies
            # Find all path-based dependencies and replace them with appropriate version constraints
            if grep -q "path =" pyproject.toml; then
              echo "Other file-based dependencies found, replacing with version constraints"
              # Use sed to replace any other path-based dependency with ^1.0.0
              sed -i 's|{ path = "[^"]*", develop = true[^}]* }|"^1.0.0"|g' pyproject.toml
              echo "Replaced other path-based dependencies with version: ^1.0.0"
            fi
            
            # Display the modified pyproject.toml for debugging
            echo "Modified pyproject.toml:"
            cat pyproject.toml
          else
            echo "pyproject.toml not found in extension directory, skipping dependency replacement."
            exit 1
          fi

      - name: Update extension version
        if: steps.check_extension.outputs.extension_exists == 'true'
        working-directory: marketplace/quant/kozmoai_platform/extensions/${{ matrix.extension }}
        run: |
          if [ -f "pyproject.toml" ]; then
            # Add dev suffix with timestamp to version
            TIMESTAMP=$(date +%Y%m%d%H%M)
            sed -i "3s/version = \"\(.*\)\"/version = \"\1.dev$TIMESTAMP\"/" pyproject.toml
            echo "Updated version in pyproject.toml"
          else
            echo "pyproject.toml not found in extension directory, skipping version update."
            exit 1
          fi

      - name: Build extension package
        if: steps.check_extension.outputs.extension_exists == 'true'
        working-directory: marketplace/quant/kozmoai_platform/extensions/${{ matrix.extension }}
        run: |
          # Build the package
          python -m build
          echo "Built package for ${{ matrix.extension }}"
          # Restore the original pyproject.toml
          if [ -f "pyproject.toml.backup" ]; then
            mv pyproject.toml.backup pyproject.toml
            echo "Restored original pyproject.toml"
          fi

      - name: Publish extension to PyPI
        id: publish_pypi
        if: steps.check_extension.outputs.extension_exists == 'true'
        continue-on-error: true
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: marketplace/quant/kozmoai_platform/extensions/${{ matrix.extension }}/dist/
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true

      - name: Publish extension to TestPyPI if PyPI failed
        if: steps.publish_pypi.outcome == 'failure' && steps.check_extension.outputs.extension_exists == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: marketplace/quant/kozmoai_platform/extensions/${{ matrix.extension }}/dist/
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

  deploy-providers:
    name: Build and publish ${{ matrix.provider }} provider 📦 to PyPI
    runs-on: ubuntu-latest
    needs: deploy-pandas-ta-kozmoai
    strategy:
      fail-fast: false
      matrix:
        provider:
          - tradingeconomics
          - federal_reserve
          - seeking_alpha
          - government_us
          - alpha_vantage
          - stockgrid
          - yfinance
          - intrinio
          - benzinga
          - tradier
          - polygon
          - deribit
          - tiingo
          - nasdaq
          - multpl
          - finviz
          - econdb
          - biztoc
          - finra
          - oecd
          - fred
          - cftc
          - cboe
          - wsj
          - tmx
          - sec
          - imf
          - fmp
          - eia
          - ecb
          - bls
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: >-
          python -m
          pip install
          build
          poetry
          toml
          yq

      - name: Verify provider directory exists
        id: check_provider
        run: |
          if [ -d "marketplace/quant/kozmoai_platform/providers/${{ matrix.provider }}" ]; then
            echo "provider_exists=true" >> $GITHUB_OUTPUT
          else
            echo "provider_exists=false" >> $GITHUB_OUTPUT
            echo "Provider ${{ matrix.provider }} directory not found, skipping."
          fi

      - name: Replace file-based dependencies with version constraints
        if: steps.check_provider.outputs.provider_exists == 'true'
        working-directory: marketplace/quant/kozmoai_platform/providers/${{ matrix.provider }}
        run: |
          if [ -f "pyproject.toml" ]; then
            # Create a backup of the original pyproject.toml
            cp pyproject.toml pyproject.toml.backup
            
            # Check if file contains pandas-ta-kozmoai as a file reference
            if grep -q "pandas-ta-kozmoai.*path" pyproject.toml; then
              echo "Found file-based pandas-ta-kozmoai dependency, replacing with version reference"
              # Replace the file-based dependency with the version from previous job
              PANDAS_TA_VERSION="${{ needs.deploy-pandas-ta-kozmoai.outputs.PANDAS_TA_VERSION || '0.4.21' }}"
              
              # Use sed to replace the path-based dependency with a version constraint
              sed -i 's|pandas-ta-kozmoai = { path = "[^"]*", develop = true }|pandas-ta-kozmoai = "'"$PANDAS_TA_VERSION"'"|g' pyproject.toml
              echo "Replaced pandas-ta-kozmoai path dependency with version: $PANDAS_TA_VERSION"
              
              # Add the appropriate index-url if using TestPyPI
              if [ "${{ needs.deploy-pandas-ta-kozmoai.outputs.REPOSITORY }}" = "testpypi" ]; then
                # Add a pyproject.toml section for the test.pypi.org index
                awk 'BEGIN{p=1}/\[build-system\]/{print "[tool.poetry.source.testpypi]\nname = \"testpypi\"\nurl = \"https://test.pypi.org/simple/\"\npriority = \"supplemental\"\n"}p' pyproject.toml > pyproject.toml.tmp
                mv pyproject.toml.tmp pyproject.toml
                echo "Added TestPyPI source to pyproject.toml"
              fi
            fi
            
            # Handle any other file-based dependencies
            # Find all path-based dependencies and replace them with appropriate version constraints
            if grep -q "path =" pyproject.toml; then
              echo "Other file-based dependencies found, replacing with version constraints"
              # Use sed to replace any other path-based dependency with ^1.0.0
              sed -i 's|{ path = "[^"]*", develop = true[^}]* }|"^1.0.0"|g' pyproject.toml
              echo "Replaced other path-based dependencies with version: ^1.0.0"
            fi
            
            # Display the modified pyproject.toml for debugging
            echo "Modified pyproject.toml:"
            cat pyproject.toml
          else
            echo "pyproject.toml not found in provider directory, skipping dependency replacement."
            exit 1
          fi

      - name: Update provider version
        if: steps.check_provider.outputs.provider_exists == 'true'
        working-directory: marketplace/quant/kozmoai_platform/providers/${{ matrix.provider }}
        run: |
          if [ -f "pyproject.toml" ]; then
            # Add dev suffix with timestamp to version
            TIMESTAMP=$(date +%Y%m%d%H%M)
            sed -i "3s/version = \"\(.*\)\"/version = \"\1.dev$TIMESTAMP\"/" pyproject.toml
            echo "Updated version in pyproject.toml"
          else
            echo "pyproject.toml not found in provider directory, skipping version update."
            exit 1
          fi

      - name: Build provider package
        if: steps.check_provider.outputs.provider_exists == 'true'
        working-directory: marketplace/quant/kozmoai_platform/providers/${{ matrix.provider }}
        run: |
          # Build the package
          python -m build
          echo "Built package for ${{ matrix.provider }}"
          # Restore the original pyproject.toml
          if [ -f "pyproject.toml.backup" ]; then
            mv pyproject.toml.backup pyproject.toml
            echo "Restored original pyproject.toml"
          fi

      - name: Publish provider to PyPI
        id: publish_pypi
        if: steps.check_provider.outputs.provider_exists == 'true'
        continue-on-error: true
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: marketplace/quant/kozmoai_platform/providers/${{ matrix.provider }}/dist/
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true

      - name: Publish provider to TestPyPI if PyPI failed
        if: steps.publish_pypi.outcome == 'failure' && steps.check_provider.outputs.provider_exists == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: marketplace/quant/kozmoai_platform/providers/${{ matrix.provider }}/dist/
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
